### ISSUE TITLE
Case sensitive file system issues

### ISSUE THREAD

**Issue by mlloewen** [Core-LOVE/SMR-Love2d#1]
On Linux, which uses case sensitive file system I get the following error. If I rename the the effected files from mCurser0.png to MCurser0.png etc.  the error goes away and loads correctly. Thanks. Great start by the way.

> Error: scripts/base/engine/graphics.lua:90: Could not open file graphics/ui/MCursor0.png. Does not exist.
> 
> stack traceback:
> 	[string "boot.lua"]:777: in function <[string "boot.lua"]:773>
> 	[C]: in function 'newImage'
> 	scripts/base/engine/graphics.lua:90: in function 'loadUi'
> 	main.lua:78: in function 'load'
> 	[string "boot.lua"]:586: in function <[string "boot.lua"]:585>
> 	[C]: in function 'xpcall'
> 	[string "boot.lua"]:793: in function <[string "boot.lua"]:780>
> 	[C]: in function 'xpcall'

**Comment by Core-LOVE** [comment]
Whops, that will be fixed! Thanks for reporting!
